-- Une requête telle qu'envoyée par un navigateur (12 en-têtes, ~650 octets).
wrk.headers["User-Agent"] = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
wrk.headers["Accept"] = "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
wrk.headers["Accept-Language"] = "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7"
wrk.headers["Accept-Encoding"] = "gzip, deflate, br, zstd"
wrk.headers["Cookie"] = "session=3f9a1c2e8b7d4f60a1b2c3d4e5f60718; theme=dark; _ga=GA1.1.123456789.1700000000"
wrk.headers["Referer"] = "https://exemple.fr/accueil"
wrk.headers["Cache-Control"] = "no-cache"
wrk.headers["Sec-Fetch-Dest"] = "document"
wrk.headers["Sec-Fetch-Mode"] = "navigate"
wrk.headers["Sec-Fetch-Site"] = "same-origin"
wrk.headers["Upgrade-Insecure-Requests"] = "1"
wrk.headers["Connection"] = "keep-alive"
